name: Build projct and deploy to Azure blob storage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: pwd
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
    - run: pwd
    - run: ls
    - run: ls public
    - uses: bacongobbler/azure-blob-storage-upload@v1.1.1
      with:
        source_dir: /home/runner/work/joseph-mcallister.github.io/joseph-mcallister.github.io/public
        container_name: $web
        connection_string: ${{ secrets.ConnectionString }}
        sync: false